# Kubernetes MCP Server Configuration with Rancher Integration

# Multi-cluster support - where to store downloaded kubeconfig files
kubeconfig_dir = "/Users/jdambly/.mcp"
auto_discovery = true

# Rancher Integration - direct API access
[rancher]
enabled = true
url = "https://rancher.prime.iad0.netskope.com"
token = "token-64l2k:dfnjc76lcgthfn8s4wlzqmpjsvfljvxtgvqb2224z2bmkzsrx4qszx"
insecure = true
config_dir = "/Users/jdambly/.mcp"

# Optional: Auto-refresh clusters periodically
# auto_refresh = true
# refresh_interval = "1h"

# Optional: Cluster filtering
# cluster_pattern = "^c[0-9]+-.*"  # Only clusters matching this regex
# exclude_clusters = ["local", "test-cluster"]
# include_clusters = ["c1-dfw1", "c2-iad0"]