kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./_output/cert-manager-ca/ca.crt
    containerPath: /etc/kubernetes/pki/keycloak-ca.crt
    readOnly: true
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        oidc-issuer-url: https://keycloak.127-0-0-1.sslip.io:8443/realms/openshift
        oidc-client-id: openshift
        oidc-username-claim: preferred_username
        oidc-groups-claim: groups
        oidc-ca-file: /etc/kubernetes/pki/keycloak-ca.crt
  extraPortMappings:
  - containerPort: 80
    hostPort: 8000
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
