name: release
on:
  push:
    tags: [ 'v*' ]
jobs:
  release:
    uses: netSkopePlatformEng/reusable-gh-actions/.github/workflows/go-release.yaml@main
    with:
      create-git-tag: false
      docker-repository: "pe-docker/kubernetes-mcp-server"
      notification_emails: jdambly@netskope.com
      release-china: true
      runs-on: "pe-org"
      upload-debs-commercial: false
      upload-debs-fedramp: false
      version-base: v1.0
    secrets: inherit